import {
  getFetchingActionCreators,
} from './util';

// FETCH COMMENTS FOR POST
export const FETCH_COMMENTS_FOR_POST = 'FETCH_COMMENTS_FOR_POST';
const FETCH_COMMENTS_FOR_POST_URL = `${process.env.REACT_APP_BACKEND}/posts/:id/comments`;
export const { ATTEMPTING_FETCH_COMMENTS_FOR_POST, SUCCESS_FETCH_COMMENTS_FOR_POST, FAILURE_FETCH_COMMENTS_FOR_POST, fetchCommentsForPost } = getFetchingActionCreators(FETCH_COMMENTS_FOR_POST, FETCH_COMMENTS_FOR_POST_URL);

// FETCH COMMENT BY ID
export const FETCH_COMMENTS_BY_ID = 'FETCH_COMMENTS_BY_ID';
const FETCH_COMMENTS_BY_ID_URL = `${process.env.REACT_APP_BACKEND}/comments/:id`;
export const { ATTEMPTING_FETCH_COMMENTS_BY_ID, SUCCESS_FETCH_COMMENTS_BY_ID, FAILURE_FETCH_COMMENTS_BY_ID, fetchCommentsById } = getFetchingActionCreators(FETCH_COMMENTS_BY_ID, FETCH_COMMENTS_BY_ID_URL);

// ADD NEW COMMENT
export const ADD_COMMENT = 'ADD_COMMENT';
const ADD_COMMENT_URL = `${process.env.REACT_APP_BACKEND}/comments`;
export const { ATTEMPTING_ADD_COMMENT, SUCCESS_ADD_COMMENT, FAILURE_ADD_COMMENT, addComment } = getFetchingActionCreators(ADD_COMMENT, ADD_COMMENT_URL, 'POST');

// VOTE FOR COMMENT
export const VOTE_FOR_COMMENT = 'VOTE_FOR_COMMENT';
const VOTE_FOR_COMMENT_URL = `${process.env.REACT_APP_BACKEND}/comments/:id`;
export const { ATTEMPTING_VOTE_FOR_COMMENT, SUCCESS_VOTE_FOR_COMMENT, FAILURE_VOTE_FOR_COMMENT, voteForComment } = getFetchingActionCreators(VOTE_FOR_COMMENT, VOTE_FOR_COMMENT_URL, 'POST');

// EDIT COMMENT
export const EDIT_COMMENT = 'EDIT_COMMENT';
const EDIT_COMMENT_URL = `${process.env.REACT_APP_BACKEND}/comments/:id`;
export const { ATTEMPTING_EDIT_COMMENT, SUCCESS_EDIT_COMMENT, FAILURE_EDIT_COMMENT, editComment } = getFetchingActionCreators(EDIT_COMMENT, EDIT_COMMENT_URL, 'PUT');

// DELETE COMMENT
export const DELETE_COMMENT = 'DELETE_COMMENT';
const DELETE_COMMENT_URL = `${process.env.REACT_APP_BACKEND}/comments/:id`;
export const { ATTEMPTING_DELETE_COMMENT, SUCCESS_DELETE_COMMENT, FAILURE_DELETE_COMMENT, deleteComment } = getFetchingActionCreators(DELETE_COMMENT, DELETE_COMMENT_URL, 'DELETE');